import test from 'node:test';
import assert from 'node:assert';
import assembleProjectPipeline from '../ai/projectAssembler.js';

test('End-to-End Enterprise AI Pipeline Execution Test', async () => {
  const prompt = 'Build a high-scale multi-tenant SaaS e-commerce platform with microservices, Redis event streams, and Stripe billing';
  
  const result = await assembleProjectPipeline(prompt);
  
  assert.ok(result, 'Result should be generated by assembly pipeline');
  assert.ok(result.name, 'Project name should be present');
  assert.ok(Array.isArray(result.files), 'Result files should be an array');
  assert.ok(result.files.length > 0, 'Generated project files count should be > 0');

  const filePaths = result.files.map(f => f.path);
  
  // Verify core AI API Generator deliverables
  assert.ok(filePaths.some(p => p.includes('package.json')), 'package.json missing');
  assert.ok(filePaths.some(p => p.includes('README.md')), 'README.md missing');
  assert.ok(filePaths.some(p => p.includes('Dockerfile')), 'Dockerfile missing');
});
